### ISSUE TITLE
[zh][Umbrella] Resync to tasks/observability/metrics pages 

### ISSUE THREAD

**Issue by ydFu** [istio/istio.io#11594]
This is an umbrella issue for tasks docs that are out of sync for zh localization. 

- [x] **metrics/classify-metrics** @ydFu https://github.com/istio/istio.io/pull/11562
- [x] **metrics/customize-metrics** @ydFu https://github.com/istio/istio.io/pull/11555
- [x] **metrics/querying-metrics** @ydFu https://github.com/istio/istio.io/pull/11548
- [x] **metrics/tcp-metrics** @ydFu https://github.com/istio/istio.io/pull/11553
- [x] **metrics/using-istio-dashboard** @ydFu https://github.com/istio/istio.io/pull/11550
- [x] **metrics** @ydFu https://github.com/istio/istio.io/pull/11593

**Comment by ydFu** [comment]
All tasks/observability/metrics pages are resync.
