### ISSUE TITLE
Missing glossary entries tracking

### ISSUE THREAD

**Issue by adammil2000** [istio/istio.io#6345]
This issue exists to track all needed glossary entries for the Istio.io documentation. Please add new items here instead of creating new issues for each. Mark each when completed.

- [ ] Auto-scaling
- [ ] Blue/green deployment
- [ ] Bootstrapping
- [ ] CA plug-in
- [ ] Canary
- [ ] CSR
- [ ] Instance configuration
- [ ] Instance scaling
- [ ] Kubernetes namespace
- [ ] Mesh Configuration Protocol (MCP)
- [ ] mTLS
- [ ] Namespace isolation
- [ ] OIDC
- [ ] Principal binding
- [ ] Red/black deployments
- [ ] SDS API
- [ ] Secure naming
- [ ] Service discovery adapter
- [ ] Service subset
- [ ] Sidecar
- [ ] Sidecar injection
- [ ] SLI/SLO
- [ ] SPIFFE
- [ ] SPIRE
- [ ] SVID
- [ ] Target selector
- [ ] Traffic rewrite
- [ ] Upstream service
